# Generated by Django 5.0.3 on 2024-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='uploads/')),
                ('last_message', models.CharField(default='', max_length=255)),
                ('users', models.ManyToManyField(default=list, to='users.usermodel')),
            ],
        ),
    ]
