# Generated by Django 5.0.3 on 2024-03-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=255)),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomId', to='chats.chatmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.usermodel')),
            ],
        ),
    ]
