# Generated by Django 5.0.3 on 2024-03-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
