# Generated by Django 5.0.3 on 2024-03-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatmodel_created_at_chatmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='updated_at',
            new_name='last_message_at',
        ),
    ]
