# Generated by Django 5.0.3 on 2024-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(default='', upload_to='uploads/')),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
